export const healthHistorySuggestions = [
  "Transtorno de Panico",
  "Fobias especificas",
  "Transtorno bipolar tipo I",
  "Transtorno bipolar tipo II",
  "Transtorno ciclotimico",
  "Outros transtornos de humor",
  "Depressao",
  "Distimia",
  "Transtorno depressivo maior",
  "TEPT",
  "Transtornos alimentares",
  "Bulimia nervosa",
  "Anorexia nervosa",
  "Transtorno de compulsao alimentar",
  "Transtornos de personalidade",
  "Transtorno de personalidade borderline",
  "Transtorno de personalidade antissocial",
  "Transtorno de personalidade narcisista",
  "Transtorno de personalidade histrionico",
  "Transtorno de personalidade esquizotipica",
  "Transtorno de personalidade esquizoide",
  "Transtorno de personalidade paranoide",
  "Transtorno de personalidade evitativa",
  "Transtorno de personalidade obsessivo compulsivo",
  "Transtorno de personalidade dependente",
  "TDAH",
  "TDA",
  "TEA",
  "Transtornos de aprendizagem",
  "Fibromialgia",
  "Ovario policistico",
] as const;
